# Statistics Basics using Python

This notebook covers the fundamental statistical concepts required for Data Science.

Topics Covered:
- Mean
- Median
- Mode
- Range
- Variance
- Standard Deviation
- Quartiles
- Percentiles
- Outlier Detection (IQR)
- Correlation

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = {"marks":[45,52,56,61,60,65,70,72,75,150],
       "study_hours":[2,3,4,5,5,6,7,8,8,10]}
df = pd.DataFrame(data)
df

   marks  study_hours
0     45            2
1     52            3
2     56            4
3     61            5
4     60            5
5     65            6
6     70            7
7     72            8
8     75            8
9    150           10

In [ ]:
print("Mean:",df["marks"].mean())

Mean: 70.6

In [ ]:
print("Median:",df["marks"].median())

Median: 63.0

In [ ]:
print("Mode:")
print(df["marks"].mode())

Mode:
0     45
1     52
2     56
3     60
4     61
5     65
6     70
7     72
8     75
9    150
Name: marks, dtype: int64

In [ ]:
range= df["marks"].max() - df["marks"].min()
print("Range:",range)

Range: 105

In [ ]:
print("Variance:", df["marks"].var())

Variance: 864.0444444444444

In [ ]:
print("Standard Deviation:", df["marks"].std())

Standard Deviation: 29.394632919028677

In [ ]:
print(df["marks"].quantile([0.25,0.50,0.75]))

0.25    57.0
0.50    63.0
0.75    71.5
Name: marks, dtype: float64

In [ ]:
print("90th Percentile")

print(df["marks"].quantile(0.90))

90th Percentile
82.49999999999997

In [ ]:
Q1 = df["marks"].quantile(0.25)

Q3 = df["marks"].quantile(0.75)

IQR = Q3 - Q1

Outlier_lower = Q1 - 1.5 * IQR

Outlier_upper = Q3 + 1.5 * IQR

outliers = df[(df["marks"] < Outlier_lower) | (df["marks"] > Outlier_upper)]

print(outliers)

   marks  study_hours
9    150           10

In [ ]:
df.corr()

                marks  study_hours
marks        1.000000     0.815455
study_hours  0.815455     1.000000

## Business Insights

- Mean represents the average marks.
- Median is less affected by outliers.
- 150 is detected as an outlier using the IQR method.
- Marks and Study Hours show a positive correlation.
- As study hours increase, marks generally increase.

# 🎯Interview Takeaways

1. Mean is affected by outliers.
2. Median is preferred for skewed data.
3. Standard Deviation measures spread.
4. Correlation does not imply causation.
5. IQR is commonly used for outlier detection.
6. Statistics forms the foundation of Data Science.