In [1]:
import pandas as pd
import numpy as np

In [2]:

data = {
    "Customer_ID": [101, 102, 103, 103, 104, 105, 106, 107],
    "Age": [25, np.nan, 28, 28, 40, 35, 29, 31],
    "Gender": ["Female", "Male", "Female", "Female", "Male", "Female", "Male", "Female"],
    "City": ["Hyderabad", "Chennai", "Hyderabad", "Hyderabad", "Bangalore", "Delhi", "Mumbai", "Chennai"],
    "Monthly_Spend": [2500, 3200, 3200, 3200, 4500, 1800, "3000", 2700],
    "Complaints": [1, 2, 2, 2, 15, 5, 1, np.nan],
    "Membership": ["Gold", "Silver", "Silver", "Silver", "Gold", "Bronze", "Silver", "Gold"],
    "Churn": ["No", "Yes", "Yes", "Yes", "No", "Yes", "No", "No"]
}

df = pd.DataFrame(data)

# Display the dataset
df

,Customer_ID,Age,Gender,City,Monthly_Spend,Complaints,Membership,Churn
0,101,25.0,Female,Hyderabad,2500,1.0,Gold,No
1,102,NaN,Male,Chennai,3200,2.0,Silver,Yes
2,103,28.0,Female,Hyderabad,3200,2.0,Silver,Yes
3,103,28.0,Female,Hyderabad,3200,2.0,Silver,Yes
4,104,40.0,Male,Bangalore,4500,15.0,Gold,No
5,105,35.0,Female,Delhi,1800,5.0,Bronze,Yes
6,106,29.0,Male,Mumbai,3000,1.0,Silver,No
7,107,31.0,Female,Chennai,2700,NaN,Gold,No

In [3]:
df.head()

,Customer_ID,Age,Gender,City,Monthly_Spend,Complaints,Membership,Churn
0,101,25.0,Female,Hyderabad,2500,1.0,Gold,No
1,102,NaN,Male,Chennai,3200,2.0,Silver,Yes
2,103,28.0,Female,Hyderabad,3200,2.0,Silver,Yes
3,103,28.0,Female,Hyderabad,3200,2.0,Silver,Yes
4,104,40.0,Male,Bangalore,4500,15.0,Gold,No

In [4]:
df.shape

(8, 8)

In [5]:
df.columns

Index(['Customer_ID', 'Age', 'Gender', 'City', 'Monthly_Spend', 'Complaints',
       'Membership', 'Churn'],
      dtype='object')

In [6]:
df.describe()

       Customer_ID        Age  Complaints
count      8.00000   7.000000    7.000000
mean     103.87500  30.857143    4.000000
std        2.03101   5.080307    5.033223
min      101.00000  25.000000    1.000000
25%      102.75000  28.000000    1.500000
50%      103.50000  29.000000    2.000000
75%      105.25000  33.000000    3.500000
max      107.00000  40.000000   15.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    8 non-null      int64
 1   Age            7 non-null      float64
 2   Gender         8 non-null      object
 3   City           8 non-null      object
 4   Monthly_Spend  8 non-null      object
 5   Complaints     7 non-null      float64
 6   Membership     8 non-null      object
 7   Churn          8 non-null      object
dtypes: float64(2), int64(1), object(5)
memory usage: 644.0+ bytes

In [8]:
df.isnull().sum()

Customer_ID      0
Age              1
Gender           0
City             0
Monthly_Spend    0
Complaints       1
Membership       0
Churn            0
dtype: int64

In [9]:
df['Complaints'].fillna(df['Complaints'].median(),inplace=True)

/tmp/ipykernel_983/410971584.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Complaints'].fillna(df['Complaints'].median(),inplace=True)

In [10]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

/tmp/ipykernel_983/1275544653.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [11]:
df

,Customer_ID,Age,Gender,City,Monthly_Spend,Complaints,Membership,Churn
0,101,25.000000,Female,Hyderabad,2500,1.0,Gold,No
1,102,30.857143,Male,Chennai,3200,2.0,Silver,Yes
2,103,28.000000,Female,Hyderabad,3200,2.0,Silver,Yes
3,103,28.000000,Female,Hyderabad,3200,2.0,Silver,Yes
4,104,40.000000,Male,Bangalore,4500,15.0,Gold,No
5,105,35.000000,Female,Delhi,1800,5.0,Bronze,Yes
6,106,29.000000,Male,Mumbai,3000,1.0,Silver,No
7,107,31.000000,Female,Chennai,2700,2.0,Gold,No

In [15]:
df[df.duplicated()]

,Customer_ID,Age,Gender,City,Monthly_Spend,Complaints,Membership,Churn
3,103,28.0,Female,Hyderabad,3200,2.0,Silver,Yes

In [16]:
df.drop_duplicates()

,Customer_ID,Age,Gender,City,Monthly_Spend,Complaints,Membership,Churn
0,101,25.000000,Female,Hyderabad,2500,1.0,Gold,No
1,102,30.857143,Male,Chennai,3200,2.0,Silver,Yes
2,103,28.000000,Female,Hyderabad,3200,2.0,Silver,Yes
4,104,40.000000,Male,Bangalore,4500,15.0,Gold,No
5,105,35.000000,Female,Delhi,1800,5.0,Bronze,Yes
6,106,29.000000,Male,Mumbai,3000,1.0,Silver,No
7,107,31.000000,Female,Chennai,2700,2.0,Gold,No

In [19]:
# Convert Monthly_Spend to integer
df["Monthly_Spend"] = df["Monthly_Spend"].astype(int)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    8 non-null      int64
 1   Age            8 non-null      float64
 2   Gender         8 non-null      object
 3   City           8 non-null      object
 4   Monthly_Spend  8 non-null      int64
 5   Complaints     8 non-null      float64
 6   Membership     8 non-null      object
 7   Churn          8 non-null      object
dtypes: float64(2), int64(2), object(4)
memory usage: 644.0+ bytes

In [29]:
Q1 = df["Complaints"].quantile(0.25) # This means 25% of the complaint values are less than or equal to 1.75.
Q3 = df["Complaints"].quantile(0.75) #This means 75% of the complaint values are less than or equal to 2.75.
print("Q1:", Q1)
print("Q3:", Q3)
IQR = Q3 - Q1 # 2.75 -1.75 =1

lower = Q1 - 1.5 * IQR #1.75-1.5*1
upper = Q3 + 1.5 * IQR #1.75+1.5*1

outliers = df[(df["Complaints"] < lower) | (df["Complaints"] > upper)]
#Show me every row where the complaint count is less than the lower limit OR greater than the upper limit.

outliers

Q1: 1.75
Q3: 2.75

,Customer_ID,Age,Gender,City,Monthly_Spend,Complaints,Membership,Churn
4,104,40.0,Male,Bangalore,4500,15.0,Gold,No
5,105,35.0,Female,Delhi,1800,5.0,Bronze,Yes

In [22]:
numerical_feature = ['Age','Complaints','Monthly_Spend']
categorical_feature = ['Gender','City','Membership']
target = 'churn'
print('numerical_feature',numerical_feature)
print('categorical_feature',categorical_feature)
print('target',target)

numerical_feature ['Age', 'Complaints', 'Monthly_Spend']
categorical_feature ['Gender', 'City', 'Membership']
target churn

In [23]:
df['Age'].mean()
df['Age'].median()
df['Age'].mode()

0    28.0
Name: Age, dtype: float64

In [24]:
df["Monthly_Spend"].mean()

df["Monthly_Spend"].median()

3100.0

In [25]:
df["Membership"].value_counts()

Membership
Silver    4
Gold      3
Bronze    1
Name: count, dtype: int64

In [26]:
df["Churn"].value_counts()

Churn
No     4
Yes    4
Name: count, dtype: int64

In [34]:
df.groupby("Churn")["Complaints"].mean()

Churn
No     4.75
Yes    2.75
Name: Complaints, dtype: float64

In [32]:
df.groupby("Churn")["Monthly_Spend"].mean()

Churn
No     3175.0
Yes    2850.0
Name: Monthly_Spend, dtype: float64

In [33]:
pd.crosstab(df["Membership"], df["Churn"])

Churn       No  Yes
Membership
Bronze       0    1
Gold         3    0
Silver       1    3

In [28]:
df.groupby(["Membership", "Churn"])[["Age", "Complaints", "Monthly_Spend"]].mean()
#Gold + Yes Gold + No Silver + Yes Silver + No Bronze + Yes and mean of the all numerical data with the mean

                        Age  Complaints  Monthly_Spend
Membership Churn
Bronze     Yes    35.000000         5.0    1800.000000
Gold       No     32.000000         6.0    3233.333333
Silver     No     29.000000         1.0    3000.000000
           Yes    28.952381         2.0    3200.000000

# Business Insights

### Insight 1
The Age column had missing values, which were filled using the median to avoid losing valuable customer records.

### Insight 2
One duplicate customer record was found and removed to prevent biased analysis.

### Insight 3
The Monthly_Spend column was converted from string to integer so numerical calculations such as averages and correlations could be performed.

### Insight 4
A customer with 15 complaints was identified as a potential outlier. Since this could represent a genuinely dissatisfied customer, it should be investigated rather than removed immediately.

### Insight 5
Customers with higher complaint counts appear more likely to churn, suggesting that improving customer support could help reduce churn.

# Module_02_EDA

01_EDA_Data_Cleaning_Part1.ipynb

1. Import Libraries
2. Create Dataset
3. Dataset Overview
4. Missing Values
5. Duplicate Rows
6. Data Types
7. Data Type Conversion
8. Outlier Detection
9. Feature Understanding
10. Univariate Analysis
11. Bivariate Analysis
12. Multivariate Analysis
13. Business Insights